# Generated by Django 3.1.4 on 2020-12-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128)),
                ('user_name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('phone_number', models.IntegerField()),
                ('address', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'tbl_users',
            },
        ),
    ]
